<a href="https://colab.research.google.com/github/Satyake/NLP/blob/master/NLP_Model_construct(Sentiment%20Analysis-PreDeployment).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd 
import numpy as np 
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from gensim.models import Word2Vec
from nltk.stem import WordNetLemmatizer
import pickle
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.layers import Embedding,LeakyReLU
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from keras import optimizers

data_train=pd.read_csv('/content/train.csv',encoding='ISO-8859-1')
data_test=pd.read_csv('/content/test.csv',encoding='ISO-8859-1')
LE=LabelEncoder()
x=data_train.iloc[:,[2]].values
y=data_train.iloc[:,[3]].values

y=LE.fit_transform(y)
x=x.tolist()
LEMMATIZER=WordNetLemmatizer()
corpus=[]
for i in range(0,len(x)):
    lines=re.sub('[^a-zA-Z]',' ',str(x[i]))
    #lines=line.sub('https?:\/\/.*[\r\n]*','',lines)
    lines=lines.lower()
    lines=lines.split()
    lines=[LEMMATIZER.lemmatize(j) for j in lines if j not in stopwords.words('english')]
    lines=' '.join(lines)
    corpus.append(lines)
len(corpus)
sentence_length=50
OHR=[one_hot(k,4000) for k in corpus]
embeddings=pad_sequences(OHR,sentence_length)

x_train,x_test,y_train,y_test=train_test_split(embeddings,y,train_size=0.7,shuffle=True)


from keras.layers import Dense
from keras.models import Sequential
from keras.layers import LSTM,Bidirectional
model=Sequential()
model.add(Embedding(4000,20,input_length=sentence_length))
model.add(Bidirectional(LSTM(30,activation='tanh',return_sequences=True)))
model.add(LeakyReLU(alpha=0.3))
model.add(LSTM(20,activation='tanh',return_sequences=False))
model.add(Dense(5,activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=40,batch_size=15)


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Epoch 1/40
7283/7283 [==============================] - 76s 10ms/step - loss: 1.1617 - accuracy: 0.5386 - val_loss: 1.0044 - val_accuracy: 0.5937
Epoch 2/40
7283/7283 [==============================] - 69s 9ms/step - loss: 0.9610 - accuracy: 0.6135 - val_loss: 0.9643 - val_accuracy: 0.6094
Epoch 3/40
7283/7283 [==============================] - 69s 9ms/step - loss: 0.9033 - accuracy: 0.6371 - val_loss: 0.9482 - val_accuracy: 0.6161
Epoch 4/40
7283/7283 [==============================] - 68s 9ms/step - loss: 0.8650 - accuracy: 0.6529 - val_loss: 0.9413 - val_accuracy: 0.6187
Epoch 5/40
7283/7283 [==============================] - 68s 9ms/step - loss: 0.8270 - accuracy: 0.6679 - val_loss: 0.9374 - val_accuracy: 0.6208
Epoch 6/40
7283/7283 [==============================] - 68s 9ms/step - loss: 0.8052 - accuracy: 0.6770 - val_loss: 0.9372 - val_accuracy: 0.6260
Epoch 7/40
7283/7283 [==============================] - 69s 9ms/step - loss: 0.7795 - accuracy: 0.6875 - val_loss: 0.9350 - val_a

KeyboardInterrupt: ignored

In [ ]:
import pandas as pd 
import numpy as np 
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from gensim.models import Word2Vec
from nltk.stem import WordNetLemmatizer
import pickle
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.layers import Embedding,LeakyReLU
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
data=pd.read_csv('all-data.csv',encoding='ISO-8859-1')
LE=LabelEncoder()
y=data.iloc[:,[0]].values
x=data.iloc[:,[1]].values
y=LE.fit_transform(y)
x=x.tolist()
LEMMATIZER=WordNetLemmatizer()
corpus=[]
for i in range(0,len(x)):
    lines=re.sub('[^a-zA-Z]',' ',str(x[i]))
    #lines=line.sub('https?:\/\/.*[\r\n]*','',lines)
    lines=lines.lower()
    lines=lines.split()
    lines=[LEMMATIZER.lemmatize(j) for j in lines if j not in stopwords.words('english')]
    lines=' '.join(lines)
    corpus.append(lines)
len(corpus)
vectors=Word2Vec(corpus)
sentence_length=80
OHR=[one_hot(k,4000) for k in corpus]
embeddings=pad_sequences(OHR,sentence_length)
GNB=GaussianNB()

x_train,x_test,y_train,y_test=train_test_split(embeddings,y,train_size=0.7,shuffle=True)
GNB.fit(x_train,y_train)
predicted=GNB.predict(x_test)
RFC=RandomForestClassifier()
RFC.fit(x_train,y_train)
predicted_rf=RFC.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(predicted_rf,y_test)

from keras.layers import Dense
from keras.models import Sequential
from keras.layers import LSTM,Bidirectional
model=Sequential()
model.add(Embedding(4000,30,input_length=sentence_length))
model.add(Bidirectional(LSTM(300,activation='relu',return_sequences=True)))
model.add(LeakyReLU(alpha=0.3))
model.add(LSTM(200,activation='relu',return_sequences=False))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=40,batch_size=15)


model.save('NLPTrained.h5')
corpus1=[]
preds=model.predict(x_test)
preds= np.argmax(preds,axis=-1)
accuracy_score(preds,y_test)
confusion_matrix(preds,y_test)

unknown='Alas '
unknown=np.array(unknown)
lines1=re.sub('[^a-zA-Z]',' ',str(unknown))
      #lines=line.sub('https?:\/\/.*[\r\n]*','',lines)
lines1=lines1.lower()
lines1=lines1.split()
lines1=[LEMMATIZER.lemmatize(j) for j in lines1 if j not in stopwords.words('english')]
lines1=' '.join(lines1)
corpus1.append(lines1)
OHR=[one_hot(k,4000) for k in corpus1]
embeddings=pad_sequences(OHR,sentence_length)
embeddings=embeddings.reshape(-1,1)
embeddings=np.transpose(embeddings)
predicted=model.predict(embeddings)
np.argmax(predicted,axis=-1)
















/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Epoch 1/40
221/227 [============================>.] - ETA: 1s - loss: nan - accuracy: 0.5677

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(embeddings,y,train_size=0.7,shuffle=True)
GNB.fit(x_train,y_train)
from sklearn.svm import SVC
SVM=SVC()
SVM.fit(x_train,y_train)
pred_svm=SVM.predict(x_test)
predicted=GNB.predict(x_test)
RFC=RandomForestClassifier()
RFC.fit(x_train,y_train)
predicted_rf=RFC.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(predicted_rf,y_test)
confusion_matrix(predicted,y_test)

array([[182, 829, 401],
       [  0,   2,   0],
       [  5,  24,  11]])

In [ ]:
model.save('NLPTrained.h5')
corpus1=[]
preds=model.predict(x_test)
preds= np.argmax(preds,axis=-1)
accuracy_score(preds,y_test)
confusion_matrix(preds,y_test)

array([[ 11,   2,  12],
       [ 71, 702, 208],
       [ 97, 141, 210]])

In [ ]:
x_test

array([[   0,    0,    0, ..., 2975, 1978, 2975],
       [   0,    0,    0, ...,   60, 3789, 2878],
       [   0,    0,    0, ...,  152, 1025, 2060],
       ...,
       [   0,    0,    0, ..., 3607, 3223,   60],
       [   0,    0,    0, ..., 2659, 1497, 3307],
       [   0,    0,    0, ..., 1403,  189, 2735]], dtype=int32)

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True